# Generated by Django 4.1.12 on 2024-01-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nilam',
            old_name='studentID',
            new_name='studentID_id',
        ),
    ]
